[package]
name = "bitsy"
version = "0.1.0"
edition = "2021"

[dependencies.rand]
version = "0.8.5"
features = ["nightly", "min_const_gen"]

[dependencies.num]
version = "0.4.0"

[profile.dev]
opt-level = 3
overflow-checks = true
codegen-units = 1
